/**************************************************************************/
/**************************************************************************/
/***************** Author: 	  Youssef Mohammed AbdelFattah ****************/
/***************** Component: TIMER1 	  				   ****************/
/***************** File: 	  TIMER1_program.c 			   ****************/
/***************** Layer: 	  MCAL 						   ****************/
/***************** Version:   1.0 						   ****************/
/**************************************************************************/
/**************************************************************************/


#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "TIMER1_private.h"
#include "TIMER1_interface.h"
#include "TIMER1_config.h"

#ifndef 	NULL
#define 	NULL (void *)0				  // NULL Equal 0 as pointer to void
#endif

void (*(TIMER1_TCNT1CallBack_PF))(void) = NULL;
void (*(TIMER1_OCR1ACallBack_PF))(void) = NULL;
void (*(TIMER1_OCR1BCallBack_PF))(void) = NULL;
void (*(TIMER1_ICR1CallBack_PF))(void)  = NULL;

/******************** INITIALZE TIMER1 ********************/
void TIMER1_voidInitialization(){
	#if 	TIMER1_WAVEFORM_GENERATION_MODE == NORMAL_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if 	TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_OC1B_ON_COMPARE_MATCH
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == CLEAR_OC1A_OC1B_ON_COMPARE_MATCH
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == SET_OC1A_OC1B_ON_COMPARE_MATCH
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 NORMAL COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_PHASE_CORRECT_8_BIT_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PHASE CORRECT PWM 8 BIT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_PHASE_CORRECT_9_BIT_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PHASE CORRECT PWM 9 BIT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_PHASE_CORRECT_10_BIT_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PHASE CORRECT PWM 10 BIT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == CTC_OCR1A_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if 	TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_OC1B_ON_COMPARE_MATCH
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == CLEAR_OC1A_OC1B_ON_COMPARE_MATCH
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == SET_OC1A_OC1B_ON_COMPARE_MATCH
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF CTC OCR1A COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == FAST_PWM_8_BIT_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 FAST PWM 8 BIT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == FAST_PWM_9_BIT_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 FAST PWM 9 BIT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == FAST_PWM_10_BIT_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		CLR_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 FAST PWM 10 BIT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_ICR1_PHASE_AND_FREQUENCY_CORRECT_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		SET(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PWM ICR1 PHASE AND FREQUENCY CORRECT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_OCR1A_PHASE_AND_FREQUENCY_CORRECT_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		SET_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PWM OCR1A PHASE AND FREQUENCY CORRECT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_ICR1_PHASE_CORRECT_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		SET_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PWM ICR1 PHASE CORRECT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == PWM_OCR1A_PHASE_CORRECT_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		CLR_BIT(TCCR1B ,TCCR1B_WGM12);
		SET_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 PWM OCR1A PHASE CORRECT COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == CTC_ICR1_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		CLR_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		SET_BIT(TCCR1B ,TCCR1B_WGM13);
		#if 	TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_OC1B_ON_COMPARE_MATCH
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == CLEAR_OC1A_OC1B_ON_COMPARE_MATCH
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif 	TIMER1_COMPARE_OUTPUT_MODE == SET_OC1A_OC1B_ON_COMPARE_MATCH
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF CTC ICR1 COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == FAST_PWM_ICR1_MODE
		CLR_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		SET_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 FAST PWM ICR1 COMPARE OUTPUT MODE!"
		#endif
	#elif 	TIMER1_WAVEFORM_GENERATION_MODE == FAST_PWM_OCR1A_MODE
		SET_BIT(TCCR1A ,TCCR1A_WGM10);
		SET_BIT(TCCR1A ,TCCR1A_WGM11);
		SET_BIT(TCCR1B ,TCCR1B_WGM12);
		SET_BIT(TCCR1B ,TCCR1B_WGM13);
		#if TIMER1_COMPARE_OUTPUT_MODE == OC1A_OC1B_DISCONNECTED
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == TOGGLE_OC1A_ON_COMPARE_MATCH_OC1B_DISCONNECTED
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1A1);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == NON_INVERTING_MODE
			CLR_BIT(TCCR1A ,TCCR1A_COM1A0);
			CLR_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#elif TIMER1_COMPARE_OUTPUT_MODE == INVERTING_MODE
			SET_BIT(TCCR1A ,TCCR1A_COM1A0);
			SET_BIT(TCCR1A ,TCCR1A_COM1B0);
			SET_BIT(TCCR1A ,TCCR1A_COM1A1);
			SET_BIT(TCCR1A ,TCCR1A_COM1B1);
		#else
			#error 	"WRONG CHOICE OF TIMER1 FAST PWM OCR1A COMPARE OUTPUT MODE!"
		#endif
	#else
		#error 	"WRONG CHOICE OF TIMER0 WAVEFORM GENERATION MODE!"
	#endif

	/***************************** Prescaller ******************************/
	#if 	TIMER0_Prescaller == TIMER_COUNTER_STOPPED
		CLR_BIT(TCCR1B ,TCCR1B_CS10);
		CLR_BIT(TCCR1B ,TCCR1B_CS11);
		CLR_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == CLKIO_NO_PRESCALLING
		SET_BIT(TCCR1B ,TCCR1B_CS10);
		CLR_BIT(TCCR1B ,TCCR1B_CS11);
		CLR_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == CLKIO8_FROM_PRESCALLER
		CLR_BIT(TCCR1B ,TCCR1B_CS10);
		SET_BIT(TCCR1B ,TCCR1B_CS11);
		CLR_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == CLKIO64_FROM_PRESCALLER
		SET_BIT(TCCR1B ,TCCR1B_CS10);
		SET_BIT(TCCR1B ,TCCR1B_CS11);
		CLR_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == CLKIO256_FROM_PRESCALLER
		CLR_BIT(TCCR1B ,TCCR1B_CS10);
		CLR_BIT(TCCR1B ,TCCR1B_CS11);
		SET_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == CLKIO1024_FROM_PRESCALLER
		SET_BIT(TCCR1B ,TCCR1B_CS10);
		CLR_BIT(TCCR1B ,TCCR1B_CS11);
		SET_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == EXTERNAL_CLK_F_SOURCE_ON_T0_PIN
		CLR_BIT(TCCR1B ,TCCR1B_CS10);
		SET_BIT(TCCR1B ,TCCR1B_CS11);
		SET_BIT(TCCR1B ,TCCR1B_CS12);
	#elif 	TIMER0_Prescaller == EXTERNAL_CLK_R_SOURCE_ON_T0_PIN
		SET_BIT(TCCR1B ,TCCR1B_CS10);
		SET_BIT(TCCR1B ,TCCR1B_CS11);
		SET_BIT(TCCR1B ,TCCR1B_CS12);
	#else
		#error 	"WRONG CHOICE OF TIMER1 PRESCALLER!"
	#endif
}

/******************** ENABLE TIMER1 OVERFLOW INTERRUPT *************/
void TIMER1_voidOverFlowInterruptEnable(void){
	SET_BIT(TIMSK ,TIMSK_TOIE1);
}

/******************** DISABLE TIMER1 OVERFLOW INTERRUPT ************/
void TIMER1_voidOverFlowInterruptDisable(void){
	CLR_BIT(TIMSK ,TIMSK_TOIE1);
}

/******************** ENABLE TIMER1 COMPARE B MATCH INTERRUPT *************/
void TIMER1_voidCompare_B_MatchInterruptEnable(void){
	SET_BIT(TIMSK ,TIMSK_OCIE1B);
}

/******************** DISABLE TIMER1 COMPARE B MATCH INTERRUPT *************/
void TIMER1_voidCompare_B_MatchInterruptDisable(void){
	CLR_BIT(TIMSK ,TIMSK_OCIE1B);
}

/******************** ENABLE TIMER1 COMPARE A MATCH INTERRUPT *************/
void TIMER1_voidCompare_A_MatchInterruptEnable(void){
	SET_BIT(TIMSK ,TIMSK_OCIE1A);
}

/******************** DISABLE TIMER1 COMPARE A MATCH INTERRUPT *************/
void TIMER1_voidCompare_A_MatchInterruptDisable(void){
	CLR_BIT(TIMSK ,TIMSK_OCIE1A);
}

/******************** ENABLE TIMER1 INPUT CAPTURE UNIT *************/
void TIMER1_void_ICU_InterruptEnable(void){
	SET_BIT(TIMSK ,TIMSK_TICIE1);
}

/******************** DISABLE TIMER1 INPUT CAPTURE UNIT *************/
void TIMER1_void_ICU_InterruptDisable(void){
	CLR_BIT(TIMSK ,TIMSK_TICIE1);
}

/******************** SET TCNT1 REGISTER  ********************/
void TIMER1_voidSetTCNT1(u16 val){
	TCNT1 = val;
}

/******************** SET OCR1A REGISTER  ********************/
void TIMER1_voidSetOCR1A(u16 val){
	OCR1A = val;
}

/******************** SET OCR1B REGISTER  ********************/
void TIMER1_voidSetOCR1B(u16 val){
	OCR1B = val;
}

/******************** SET ICR1 REGISTER *************/
void TIMER1_u16SetICR1(u16 val){
	ICR1 = val;
}

/******************** READ ICR1 REGISTER *************/
u16 TIMER1_u16ReadICR1(void){
	return ICR1;
}

/********* CALL BACK FUNCTION FOR TIMER1 OVERFLOW INTERRUPT *********/
void TIMER1_voidSetCallBackTCNT1(void (*Copy_PF)(void));

/******* CALL BACK FUNCTION FOR TIMER1 COMPARE MATCH A INTERRUPT ******/
void TIMER1_voidSetCallBackOCR1A(void (*Copy_PF)(void));

/******* CALL BACK FUNCTION FOR TIMER1 COMPARE MATCH B INTERRUPT ******/
void TIMER1_voidSetCallBackOCR1B(void (*Copy_PF)(void));

/********* CALL BACK FUNCTION FOR TIMER1 INPUT CAPTURE INTERRUPT *********/
void TIMER1_voidSetCallBackICR1(void (*Copy_PF)(void));


/********************* CALL BACK FUNCTION FOR TIMER1 OVERFLOW INTERRUPT *********************/
void TIMER1_voidSetCallBackTCNT1(void (*Copy_PF)(void)){
	TIMER1_TCNT1CallBack_PF = Copy_PF;
}

void __vector_9 (void) __attribute__((signal ,used));       // TIMER/COUNTER1 OVERFLOW
void __vector_9(void){
	TIMER1_TCNT1CallBack_PF();
}
/*********************************************************************************************/

/****************** CALL BACK FUNCTION FOR TIMER1 COMPARE MATCH A INTERRUPT ******************/
void TIMER1_voidSetCallBackOCR1A(void (*Copy_PF)(void)){
	TIMER1_OCR1ACallBack_PF = Copy_PF;
}

void __vector_7 (void) __attribute__((signal ,used));		// TIMER/COUNTER1 COMPARE MATCH A
void __vector_7(void){
	TIMER1_OCR1ACallBack_PF();
}
/*********************************************************************************************/

/****************** CALL BACK FUNCTION FOR TIMER1 COMPARE MATCH B INTERRUPT ******************/
void TIMER1_voidSetCallBackOCR1B(void (*Copy_PF)(void)){
	TIMER1_OCR1BCallBack_PF = Copy_PF;
}

void __vector_8 (void) __attribute__((signal ,used));		// TIMER/COUNTER1 COMPARE MATCH B
void __vector_8(void){
	TIMER1_OCR1BCallBack_PF();
}
/*********************************************************************************************/

/******************* CALL BACK FUNCTION FOR TIMER1 INPUT CAPTURE INTERRUPT *******************/
void TIMER1_voidSetCallBackICR1(void (*Copy_PF)(void)){
	TIMER1_ICR1CallBack_PF = Copy_PF;
}

void __vector_6 (void) __attribute__((signal ,used));		// TIMER/COUNTER1 INPUT CAPTURE UNIT
void __vector_6(void){
	TIMER1_ICR1CallBack_PF();
}
/*********************************************************************************************/
